using System.ComponentModel.DataAnnotations.Schema;
namespace ElloClinic.Api;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? UpdatedAt { get; set; } }
public abstract class TenantEntity : Entity { public Guid TenantId { get; set; } }
public enum UserRole { PlatformAdmin, ClinicAdmin, Reception, Professional, Finance }
public enum AppointmentStatus { PreScheduled, AwaitingConfirmation, Confirmed, Arrived, InProgress, Completed, ClinicCancelled, PatientCancelled, Rescheduled, NoShow, AwaitingPayment, Finalized }
public enum FinancialStatus { Pending, Paid, PartiallyPaid, Overdue, Cancelled, Refunded, Courtesy, Negotiating }

public sealed class Tenant : Entity { public string Name { get; set; } = ""; public string Slug { get; set; } = ""; public string? Document { get; set; } public string? Email { get; set; } public bool Active { get; set; } = true; public string PlanCode { get; set; } = "trial"; public string SubscriptionStatus { get; set; } = "trialing"; public DateTimeOffset? TrialEndsAt { get; set; } }
public sealed class AppUser : TenantEntity { public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string PasswordHash { get; set; } = ""; public UserRole Role { get; set; } public Guid? ProfessionalId { get; set; } public bool Active { get; set; } = true; }
public sealed class Unit : TenantEntity { public string Name { get; set; } = ""; public string? Address { get; set; } public bool Active { get; set; } = true; }
public sealed class Room : TenantEntity { public Guid UnitId { get; set; } public string Name { get; set; } = ""; public bool Active { get; set; } = true; }
public sealed class Specialty : TenantEntity { public string Name { get; set; } = ""; public string Color { get; set; } = "#7158E2"; public bool Active { get; set; } = true; }
public sealed class ClinicService : TenantEntity { public Guid SpecialtyId { get; set; } public string Name { get; set; } = ""; public int DurationMinutes { get; set; } = 50; public decimal Price { get; set; } public bool RequiresRoom { get; set; } = true; public bool Active { get; set; } = true; }
public sealed class Professional : TenantEntity { public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string? Phone { get; set; } public string? Council { get; set; } public string? RegistrationNumber { get; set; } public Guid SpecialtyId { get; set; } public string Color { get; set; } = "#4F7CF7"; public decimal DefaultSplitPercent { get; set; } public bool Active { get; set; } = true; [NotMapped] public bool HasAccess { get; set; } }
public sealed class Patient : TenantEntity { public string Name { get; set; } = ""; public string? SocialName { get; set; } public string? Document { get; set; } public DateOnly? BirthDate { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? ResponsibleName { get; set; } public string? ResponsiblePhone { get; set; } public string? Notes { get; set; } public bool Active { get; set; } = true; }
public sealed class Appointment : TenantEntity { public Guid PatientId { get; set; } public Guid ProfessionalId { get; set; } public Guid ServiceId { get; set; } public Guid UnitId { get; set; } public Guid? RoomId { get; set; } public DateTimeOffset StartsAt { get; set; } public DateTimeOffset EndsAt { get; set; } public AppointmentStatus Status { get; set; } public decimal Amount { get; set; } public string? Notes { get; set; } public Patient? Patient { get; set; } public Professional? Professional { get; set; } public ClinicService? Service { get; set; } }
public enum ConfirmationResponse { Confirmed, CancellationRequested, RescheduleRequested }
public sealed class AppointmentConfirmation : TenantEntity { public Guid AppointmentId { get; set; } public string TokenHash { get; set; } = ""; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? ViewedAt { get; set; } public DateTimeOffset? RespondedAt { get; set; } public ConfirmationResponse? Response { get; set; } public string? RespondentName { get; set; } public string? Message { get; set; } public string? IpAddress { get; set; } public string? UserAgent { get; set; } public Appointment? Appointment { get; set; } }
public sealed class ClinicalEvolution : TenantEntity { public Guid PatientId { get; set; } public Guid AppointmentId { get; set; } public Guid ProfessionalId { get; set; } public string Objective { get; set; } = ""; public string Activities { get; set; } = ""; public string Response { get; set; } = ""; public string Conduct { get; set; } = ""; public bool Finalized { get; set; } public DateTimeOffset? FinalizedAt { get; set; } }
public sealed class TherapeuticPlan : TenantEntity { public Guid PatientId { get; set; } public Guid ProfessionalId { get; set; } public Guid SpecialtyId { get; set; } public DateOnly StartDate { get; set; } public string MainComplaint { get; set; } = ""; public string GeneralGoals { get; set; } = ""; public string SpecificGoals { get; set; } = ""; public string RecommendedFrequency { get; set; } = ""; public DateOnly? ReassessmentDate { get; set; } public string Status { get; set; } = "Active"; public DateOnly? EndDate { get; set; } public string? ClosingReason { get; set; } }
public sealed class Receivable : TenantEntity { public Guid PatientId { get; set; } public Guid? AppointmentId { get; set; } public string Description { get; set; } = ""; public decimal Amount { get; set; } public decimal PaidAmount { get; set; } public DateOnly DueDate { get; set; } public FinancialStatus Status { get; set; } }
public sealed class Payable : TenantEntity { public string Description { get; set; } = ""; public string Category { get; set; } = ""; public decimal Amount { get; set; } public DateOnly DueDate { get; set; } public FinancialStatus Status { get; set; } }
public sealed class AuditLog : TenantEntity { public Guid? UserId { get; set; } public string Action { get; set; } = ""; public string Entity { get; set; } = ""; public string? EntityId { get; set; } public string? IpAddress { get; set; } public string? Data { get; set; } }
