using System.Text;
using System.Text.Json.Serialization;
using System.Security.Cryptography;
using System.Globalization;
using System.Text.RegularExpressions;
using ElloClinic.Api;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);
var connection = Environment.GetEnvironmentVariable("DATABASE_URL") ?? builder.Configuration.GetConnectionString("Default");
builder.Services.AddHttpContextAccessor(); builder.Services.AddScoped<ITenantContext, TenantContext>();
builder.Services.AddDbContext<ClinicDbContext>(o => o.UseNpgsql(NormalizeDatabaseUrl(connection!)));
builder.Services.AddScoped<TokenService>(); builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();
builder.Services.ConfigureHttpJsonOptions(o => o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
var jwtKey = builder.Configuration["Jwt:Key"] ?? Environment.GetEnvironmentVariable("JWT_KEY") ?? "development-only-key-change-me-32-chars";
if (!builder.Environment.IsDevelopment() && (jwtKey.Length < 32 || jwtKey.StartsWith("development-", StringComparison.Ordinal))) throw new InvalidOperationException("JWT_KEY segura não configurada.");
builder.Configuration["Jwt:Key"] = jwtKey;
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => o.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = false, ValidateAudience = false, ValidateLifetime = true, ValidateIssuerSigningKey = true, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)), RoleClaimType = System.Security.Claims.ClaimTypes.Role });
var corsOrigins = (Environment.GetEnvironmentVariable("CORS_ORIGINS") ?? builder.Configuration["Cors:Origins"] ?? (builder.Environment.IsDevelopment() ? "http://localhost:4200" : "")).Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
builder.Services.AddAuthorization(); builder.Services.AddCors(o => o.AddDefaultPolicy(p => { if (corsOrigins.Length > 0) p.WithOrigins(corsOrigins).AllowAnyHeader().AllowAnyMethod(); }));
var app = builder.Build(); app.UseExceptionHandler(handler => handler.Run(async context => { context.Response.StatusCode = StatusCodes.Status500InternalServerError; context.Response.ContentType = "application/problem+json"; await context.Response.WriteAsJsonAsync(new { title = "Não foi possível concluir a operação.", status = 500 }); })); app.UseCors(); app.UseAuthentication(); app.UseAuthorization();
if (app.Environment.IsDevelopment()) { app.UseSwagger(); app.UseSwaggerUI(); }
app.MapGet("/health", async (ClinicDbContext db) => { if (!await db.Database.CanConnectAsync()) return Results.Problem("Database unavailable", statusCode: 503); return Results.Ok(new { status = "healthy", database = "connected", utc = DateTimeOffset.UtcNow }); }).AllowAnonymous();

app.MapPost("/api/auth/login", async (LoginRequest req, ClinicDbContext db, TokenService tokens) => {
    var tenant = await db.Tenants.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.Slug == req.Tenant && x.Active); if (tenant is null) return Results.Unauthorized();
    var user = await db.Users.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.TenantId == tenant.Id && x.Email == req.Email.ToLower() && x.Active);
    return user is null || !Passwords.Verify(req.Password, user.PasswordHash) ? Results.Unauthorized() : Results.Ok(new { token = tokens.Create(user), user = new { user.Name, user.Email, role = user.Role.ToString(), tenant = tenant.Name, user.ProfessionalId, tenant.PlanCode, tenant.SubscriptionStatus, tenant.TrialEndsAt } });
}).AllowAnonymous();
app.MapPost("/api/public/trials", async (TrialRequest input, ClinicDbContext db, TokenService tokens) => {
    var name = input.ClinicName.Trim(); var adminName = input.Name.Trim(); var email = input.Email.Trim().ToLowerInvariant(); var plan = input.Plan.Trim().ToLowerInvariant();
    if (name.Length < 3 || adminName.Length < 3 || !email.Contains('@') || input.Password.Length < 8) return Results.BadRequest(new { message = "Preencha os dados e use uma senha com pelo menos 8 caracteres." });
    if (plan is not ("starter" or "professional")) return Results.BadRequest(new { message = "Plano inválido." });
    var baseSlug = Slugify(name); if (baseSlug.Length < 3) baseSlug = "clinica"; var slug = baseSlug; var suffix = 1; while (await db.Tenants.IgnoreQueryFilters().AnyAsync(x => x.Slug == slug)) slug = $"{baseSlug}-{++suffix}";
    if (await db.Users.IgnoreQueryFilters().AnyAsync(x => x.Email == email)) return Results.Conflict(new { message = "Este e-mail já possui uma conta. Acesse o sistema ou use outro e-mail." });
    var tenant = new Tenant { Name = name, Slug = slug, Email = email, PlanCode = plan, SubscriptionStatus = "trialing", TrialEndsAt = DateTimeOffset.UtcNow.AddDays(14) }; db.Tenants.Add(tenant); await db.SaveChangesAsync();
    var user = new AppUser { TenantId = tenant.Id, Name = adminName, Email = email, PasswordHash = Passwords.Hash(input.Password), Role = UserRole.ClinicAdmin }; db.Users.Add(user); db.Units.Add(new Unit { TenantId = tenant.Id, Name = "Unidade Principal" }); await db.SaveChangesAsync();
    return Results.Created($"/api/tenants/{tenant.Id}", new { token = tokens.Create(user), user = new { user.Name, user.Email, role = user.Role.ToString(), tenant = tenant.Name, professionalId = (Guid?)null, tenant.PlanCode, tenant.SubscriptionStatus, tenant.TrialEndsAt }, tenant = new { tenant.Id, tenant.Name, tenant.Slug, tenant.TrialEndsAt } });
}).AllowAnonymous();
app.MapGet("/api/public/appointments/confirmation/{token}", async (string token, ClinicDbContext db) => {
    var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));
    var confirmation = await db.AppointmentConfirmations.IgnoreQueryFilters().Include(x => x.Appointment)!.ThenInclude(x => x!.Patient).Include(x => x.Appointment)!.ThenInclude(x => x!.Professional).Include(x => x.Appointment)!.ThenInclude(x => x!.Service).SingleOrDefaultAsync(x => x.TokenHash == hash);
    if (confirmation is null) return Results.NotFound(new { message = "Link de confirmação inválido." });
    if (confirmation.ExpiresAt < DateTimeOffset.UtcNow) return Results.Json(new { message = "Este link de confirmação expirou." }, statusCode: 410);
    confirmation.ViewedAt ??= DateTimeOffset.UtcNow; await db.SaveChangesAsync(); var tenant = await db.Tenants.IgnoreQueryFilters().SingleAsync(x => x.Id == confirmation.TenantId);
    return Results.Ok(new { clinic = tenant.Name, patient = confirmation.Appointment!.Patient!.Name, professional = confirmation.Appointment.Professional!.Name, service = confirmation.Appointment.Service!.Name, confirmation.Appointment.StartsAt, confirmation.Appointment.EndsAt, status = confirmation.Appointment.Status.ToString(), responded = confirmation.RespondedAt != null, response = confirmation.Response?.ToString(), expiresAt = confirmation.ExpiresAt });
}).AllowAnonymous();
app.MapPost("/api/public/appointments/confirmation/{token}/respond", async (string token, PublicConfirmationRequest input, HttpContext http, ClinicDbContext db) => {
    var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));
    var confirmation = await db.AppointmentConfirmations.IgnoreQueryFilters().Include(x => x.Appointment).SingleOrDefaultAsync(x => x.TokenHash == hash);
    if (confirmation is null) return Results.NotFound(new { message = "Link de confirmação inválido." }); if (confirmation.ExpiresAt < DateTimeOffset.UtcNow) return Results.Json(new { message = "Este link expirou." }, statusCode: 410); if (confirmation.RespondedAt != null) return Results.Conflict(new { message = "Este agendamento já recebeu uma resposta." });
    if (!Enum.TryParse<ConfirmationResponse>(input.Response, true, out var response)) return Results.BadRequest(new { message = "Resposta inválida." });
    confirmation.Response = response; confirmation.RespondedAt = DateTimeOffset.UtcNow; confirmation.RespondentName = input.RespondentName?.Trim(); confirmation.Message = input.Message?.Trim(); confirmation.IpAddress = http.Connection.RemoteIpAddress?.ToString(); confirmation.UserAgent = http.Request.Headers.UserAgent.ToString();
    confirmation.Appointment!.Status = response switch { ConfirmationResponse.Confirmed => AppointmentStatus.Confirmed, ConfirmationResponse.CancellationRequested => AppointmentStatus.PatientCancelled, _ => AppointmentStatus.Rescheduled };
    await db.SaveChangesAsync(); return Results.Ok(new { response = response.ToString(), status = confirmation.Appointment.Status.ToString(), message = response == ConfirmationResponse.Confirmed ? "Atendimento confirmado com sucesso." : "Sua solicitação foi enviada à clínica." });
}).AllowAnonymous();

var api = app.MapGroup("/api").RequireAuthorization();
api.MapGet("/me", (HttpContext http) => Results.Ok(new { name = http.User.Identity?.Name, email = http.User.FindFirst(System.Security.Claims.ClaimTypes.Email)?.Value, role = http.User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value, professionalId = http.User.FindFirst("professional_id")?.Value }));
api.MapGet("/dashboard", async (ClinicDbContext db, HttpContext http) => { var today = DateTimeOffset.UtcNow.Date; var tomorrow = today.AddDays(1); var professionalId = ClaimGuid(http, "professional_id"); var appts = db.Appointments.Where(x => x.StartsAt >= today && x.StartsAt < tomorrow && (professionalId == null || x.ProfessionalId == professionalId)); var patientIds = db.Appointments.Where(x => professionalId == null || x.ProfessionalId == professionalId).Select(x => x.PatientId); return Results.Ok(new { appointmentsToday = await appts.CountAsync(), confirmed = await appts.CountAsync(x => x.Status == AppointmentStatus.Confirmed), completed = await appts.CountAsync(x => x.Status == AppointmentStatus.Completed), pending = professionalId == null ? await db.Receivables.Where(x => x.Status == FinancialStatus.Pending).SumAsync(x => (decimal?)x.Amount) ?? 0 : 0, received = professionalId == null ? await db.Receivables.Where(x => x.Status == FinancialStatus.Paid).SumAsync(x => (decimal?)x.PaidAmount) ?? 0 : 0, activePatients = professionalId == null ? await db.Patients.CountAsync(x => x.Active) : await db.Patients.CountAsync(x => x.Active && patientIds.Contains(x.Id)), activeProfessionals = professionalId == null ? await db.Professionals.CountAsync(x => x.Active) : 1 }); });
api.MapGet("/patients", async (string? search, ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); var query = db.Patients.Where(x => search == null || x.Name.ToLower().Contains(search.ToLower())); if (professionalId != null) { var ids = db.Appointments.Where(x => x.ProfessionalId == professionalId).Select(x => x.PatientId); query = query.Where(x => ids.Contains(x.Id)); } return await query.OrderBy(x => x.Name).ToListAsync(); });
api.MapPost("/patients", async (Patient input, ClinicDbContext db) => { input.Id = Guid.NewGuid(); db.Patients.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/patients/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception"));
api.MapPut("/patients/{id:guid}", async (Guid id, Patient input, ClinicDbContext db) => { var item = await db.Patients.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.SocialName = input.SocialName; item.Document = input.Document; item.BirthDate = input.BirthDate; item.Phone = input.Phone; item.Email = input.Email; item.ResponsibleName = input.ResponsibleName; item.ResponsiblePhone = input.ResponsiblePhone; item.Notes = input.Notes; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception"));
api.MapDelete("/patients/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Patients.FindAsync(id); if (item is null) return Results.NotFound(); item.Active = false; await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapGet("/professionals", async (ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); var items = await db.Professionals.Where(x => professionalId == null || x.Id == professionalId).OrderBy(x => x.Name).ToListAsync(); var accessIds = await db.Users.Select(x => x.ProfessionalId).Where(x => x != null).ToListAsync(); foreach (var item in items) item.HasAccess = accessIds.Contains(item.Id); return items; });
api.MapPost("/professionals", async (Professional input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/professionals/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPost("/professionals/{id:guid}/access", async (Guid id, ProfessionalAccessRequest input, ClinicDbContext db) => { var professional = await db.Professionals.FindAsync(id); if (professional is null) return Results.NotFound(); var email = input.Email.Trim().ToLowerInvariant(); if (string.IsNullOrWhiteSpace(email) || input.Password.Length < 8) return Results.BadRequest(new { message = "Informe um e-mail válido e senha com pelo menos 8 caracteres." }); var user = await db.Users.SingleOrDefaultAsync(x => x.ProfessionalId == id); if (user is null && await db.Users.AnyAsync(x => x.Email == email)) return Results.Conflict(new { message = "Este e-mail já está vinculado a outro usuário." }); if (user is null) { user = new AppUser { ProfessionalId = id, Name = professional.Name, Email = email, Role = UserRole.Professional }; db.Add(user); } user.Name = professional.Name; user.Email = email; user.PasswordHash = Passwords.Hash(input.Password); user.Role = UserRole.Professional; user.Active = true; professional.Email = email; await db.SaveChangesAsync(); return Results.Ok(new { user.Email, role = user.Role.ToString(), professionalId = id }); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPut("/professionals/{id:guid}", async (Guid id, Professional input, ClinicDbContext db) => { var item = await db.Professionals.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.Email = input.Email; item.Phone = input.Phone; item.Council = input.Council; item.RegistrationNumber = input.RegistrationNumber; item.SpecialtyId = input.SpecialtyId; item.Color = input.Color; item.DefaultSplitPercent = input.DefaultSplitPercent; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapDelete("/professionals/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Professionals.FindAsync(id); if (item is null) return Results.NotFound(); item.Active = false; await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapGet("/catalog", async (ClinicDbContext db) => Results.Ok(new { specialties = await db.Specialties.ToListAsync(), services = await db.Services.ToListAsync(), units = await db.Units.ToListAsync(), rooms = await db.Rooms.ToListAsync() }));
api.MapPost("/specialties", async (Specialty input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/specialties/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPut("/specialties/{id:guid}", async (Guid id, Specialty input, ClinicDbContext db) => { var item = await db.Specialties.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.Color = input.Color; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapDelete("/specialties/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Specialties.FindAsync(id); if (item is null) return Results.NotFound(); if (await db.Services.AnyAsync(x => x.SpecialtyId == id) || await db.Professionals.AnyAsync(x => x.SpecialtyId == id)) return Results.Conflict(new { message = "Especialidade em uso; inative-a em vez de excluir." }); db.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPost("/services", async (ClinicService input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/services/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPut("/services/{id:guid}", async (Guid id, ClinicService input, ClinicDbContext db) => { var item = await db.Services.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.SpecialtyId = input.SpecialtyId; item.DurationMinutes = input.DurationMinutes; item.Price = input.Price; item.RequiresRoom = input.RequiresRoom; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapDelete("/services/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Services.FindAsync(id); if (item is null) return Results.NotFound(); if (await db.Appointments.AnyAsync(x => x.ServiceId == id)) return Results.Conflict(new { message = "Serviço possui agendamentos e não pode ser excluído." }); db.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPost("/units", async (Unit input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/units/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPut("/units/{id:guid}", async (Guid id, Unit input, ClinicDbContext db) => { var item = await db.Units.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.Address = input.Address; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapDelete("/units/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Units.FindAsync(id); if (item is null) return Results.NotFound(); if (await db.Rooms.AnyAsync(x => x.UnitId == id) || await db.Appointments.AnyAsync(x => x.UnitId == id)) return Results.Conflict(new { message = "Unidade em uso; inative-a em vez de excluir." }); db.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPost("/rooms", async (Room input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/rooms/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapPut("/rooms/{id:guid}", async (Guid id, Room input, ClinicDbContext db) => { var item = await db.Rooms.FindAsync(id); if (item is null) return Results.NotFound(); item.Name = input.Name; item.UnitId = input.UnitId; item.Active = input.Active; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapDelete("/rooms/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Rooms.FindAsync(id); if (item is null) return Results.NotFound(); if (await db.Appointments.AnyAsync(x => x.RoomId == id)) return Results.Conflict(new { message = "Sala possui agendamentos e não pode ser excluída." }); db.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin"));
api.MapGet("/appointments", async (DateTimeOffset from, DateTimeOffset to, ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); return await db.Appointments.Include(x => x.Patient).Include(x => x.Professional).Include(x => x.Service).Where(x => x.StartsAt < to && x.EndsAt > from && (professionalId == null || x.ProfessionalId == professionalId)).OrderBy(x => x.StartsAt).ToListAsync(); });
api.MapPost("/appointments", async (Appointment input, ClinicDbContext db, HttpContext http) => {
    var ownProfessionalId = ClaimGuid(http, "professional_id"); if (ownProfessionalId != null && input.ProfessionalId != ownProfessionalId) return Results.Forbid();
    if (input.EndsAt <= input.StartsAt) return Results.ValidationProblem(new Dictionary<string,string[]> { ["period"] = ["O término deve ser posterior ao início."] });
    var active = new[] { AppointmentStatus.PreScheduled, AppointmentStatus.AwaitingConfirmation, AppointmentStatus.Confirmed, AppointmentStatus.Arrived, AppointmentStatus.InProgress };
    var conflict = await db.Appointments.AnyAsync(x => active.Contains(x.Status) && x.StartsAt < input.EndsAt && x.EndsAt > input.StartsAt && (x.ProfessionalId == input.ProfessionalId || x.PatientId == input.PatientId || (input.RoomId != null && x.RoomId == input.RoomId)));
    if (conflict) return Results.Conflict(new { message = "Conflito de profissional, paciente ou sala no período informado." });
    db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/appointments/{input.Id}", input);
}).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception", "Professional"));
api.MapPut("/appointments/{id:guid}", async (Guid id, Appointment input, ClinicDbContext db, HttpContext http) => {
    var item = await db.Appointments.FindAsync(id); if (item is null) return Results.NotFound();
    var ownProfessionalId = ClaimGuid(http, "professional_id"); if (ownProfessionalId != null && (item.ProfessionalId != ownProfessionalId || input.ProfessionalId != ownProfessionalId)) return Results.Forbid();
    if (input.EndsAt <= input.StartsAt) return Results.ValidationProblem(new Dictionary<string,string[]> { ["period"] = ["O término deve ser posterior ao início."] });
    var active = new[] { AppointmentStatus.PreScheduled, AppointmentStatus.AwaitingConfirmation, AppointmentStatus.Confirmed, AppointmentStatus.Arrived, AppointmentStatus.InProgress };
    var conflict = await db.Appointments.AnyAsync(x => x.Id != id && active.Contains(x.Status) && x.StartsAt < input.EndsAt && x.EndsAt > input.StartsAt && (x.ProfessionalId == input.ProfessionalId || x.PatientId == input.PatientId || (input.RoomId != null && x.RoomId == input.RoomId)));
    if (conflict) return Results.Conflict(new { message = "Conflito de profissional, paciente ou sala no período informado." });
    item.PatientId = input.PatientId; item.ProfessionalId = input.ProfessionalId; item.ServiceId = input.ServiceId; item.UnitId = input.UnitId; item.RoomId = input.RoomId; item.StartsAt = input.StartsAt; item.EndsAt = input.EndsAt; item.Status = input.Status; item.Amount = input.Amount; item.Notes = input.Notes;
    await db.SaveChangesAsync(); return Results.Ok(item);
}).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception", "Professional"));
api.MapDelete("/appointments/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Appointments.FindAsync(id); if (item is null) return Results.NotFound(); if (item.Status is AppointmentStatus.Completed or AppointmentStatus.Finalized) return Results.Conflict(new { message = "Atendimentos realizados não podem ser excluídos. Altere o status quando aplicável." }); item.Status = AppointmentStatus.ClinicCancelled; await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception"));
api.MapPost("/appointments/{id:guid}/confirmation-link", async (Guid id, ClinicDbContext db) => { var appointment = await db.Appointments.FindAsync(id); if (appointment is null) return Results.NotFound(); var previous = await db.AppointmentConfirmations.Where(x => x.AppointmentId == id && x.RespondedAt == null).ToListAsync(); foreach (var old in previous) old.ExpiresAt = DateTimeOffset.UtcNow; var rawToken = Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(RandomNumberGenerator.GetBytes(32)); var expires = appointment.StartsAt > DateTimeOffset.UtcNow ? appointment.StartsAt : DateTimeOffset.UtcNow.AddDays(2); var confirmation = new AppointmentConfirmation { AppointmentId = id, TokenHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(rawToken))), ExpiresAt = expires }; db.Add(confirmation); if (appointment.Status == AppointmentStatus.PreScheduled) appointment.Status = AppointmentStatus.AwaitingConfirmation; await db.SaveChangesAsync(); return Results.Ok(new { path = $"/confirmacao/{rawToken}", expiresAt = expires }); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Reception"));
api.MapPatch("/appointments/{id:guid}/status", async (Guid id, StatusRequest req, ClinicDbContext db) => { var item = await db.Appointments.FindAsync(id); if (item is null) return Results.NotFound(); item.Status = req.Status; if (req.Status == AppointmentStatus.Completed && !await db.Receivables.AnyAsync(x => x.AppointmentId == id)) db.Receivables.Add(new Receivable { PatientId = item.PatientId, AppointmentId = id, Description = "Atendimento", Amount = item.Amount, DueDate = DateOnly.FromDateTime(DateTime.Today), Status = FinancialStatus.Pending }); await db.SaveChangesAsync(); return Results.NoContent(); });
api.MapGet("/evolutions", async (ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); var query = db.Evolutions.AsQueryable(); if (professionalId != null) query = query.Where(x => x.ProfessionalId == professionalId); return await query.OrderByDescending(x => x.CreatedAt).ToListAsync(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapPost("/evolutions", async (ClinicalEvolution input, ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); if (professionalId != null && input.ProfessionalId != professionalId) return Results.Forbid(); input.FinalizedAt = input.Finalized ? DateTimeOffset.UtcNow : null; db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/evolutions/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapPut("/evolutions/{id:guid}", async (Guid id, ClinicalEvolution input, ClinicDbContext db, HttpContext http) => { var item = await db.Evolutions.FindAsync(id); if (item is null) return Results.NotFound(); var professionalId = ClaimGuid(http, "professional_id"); if (professionalId != null && item.ProfessionalId != professionalId) return Results.Forbid(); if (item.Finalized) return Results.Conflict(new { message = "Uma evolução finalizada não pode ser alterada." }); item.Objective = input.Objective; item.Activities = input.Activities; item.Response = input.Response; item.Conduct = input.Conduct; item.Finalized = input.Finalized; item.FinalizedAt = input.Finalized ? DateTimeOffset.UtcNow : null; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapGet("/medical-records", async (ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); var patientQuery = db.Patients.Where(x => x.Active); if (professionalId != null) { var ownIds = db.Appointments.Where(x => x.ProfessionalId == professionalId).Select(x => x.PatientId); patientQuery = patientQuery.Where(x => ownIds.Contains(x.Id)); } var patients = await patientQuery.OrderBy(x => x.Name).ToListAsync(); var ids = patients.Select(x => x.Id).ToArray(); var appointments = await db.Appointments.Where(x => ids.Contains(x.PatientId) && (professionalId == null || x.ProfessionalId == professionalId)).ToListAsync(); var evolutions = await db.Evolutions.Where(x => ids.Contains(x.PatientId) && (professionalId == null || x.ProfessionalId == professionalId)).ToListAsync(); return Results.Ok(patients.Select(p => new { patient = p, appointments = appointments.Count(x => x.PatientId == p.Id), evolutions = evolutions.Count(x => x.PatientId == p.Id), lastAppointment = appointments.Where(x => x.PatientId == p.Id).OrderByDescending(x => x.StartsAt).Select(x => (DateTimeOffset?)x.StartsAt).FirstOrDefault(), pendingEvolution = appointments.Count(x => x.PatientId == p.Id && x.Status == AppointmentStatus.Completed && !evolutions.Any(e => e.AppointmentId == x.Id)) })); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapGet("/medical-records/{patientId:guid}", async (Guid patientId, ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); if (professionalId != null && !await db.Appointments.AnyAsync(x => x.PatientId == patientId && x.ProfessionalId == professionalId)) return Results.Forbid(); var patient = await db.Patients.FindAsync(patientId); if (patient is null) return Results.NotFound(); var appointments = await db.Appointments.Include(x => x.Professional).Include(x => x.Service).Where(x => x.PatientId == patientId && (professionalId == null || x.ProfessionalId == professionalId)).OrderByDescending(x => x.StartsAt).ToListAsync(); var evolutions = await db.Evolutions.Where(x => x.PatientId == patientId && (professionalId == null || x.ProfessionalId == professionalId)).OrderByDescending(x => x.CreatedAt).ToListAsync(); var plans = await db.TherapeuticPlans.Where(x => x.PatientId == patientId && (professionalId == null || x.ProfessionalId == professionalId)).OrderByDescending(x => x.StartDate).ToListAsync(); return Results.Ok(new { patient, appointments, evolutions, plans }); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapPost("/therapeutic-plans", async (TherapeuticPlan input, ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); if (professionalId != null && input.ProfessionalId != professionalId) return Results.Forbid(); db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/therapeutic-plans/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapPut("/therapeutic-plans/{id:guid}", async (Guid id, TherapeuticPlan input, ClinicDbContext db, HttpContext http) => { var item = await db.TherapeuticPlans.FindAsync(id); if (item is null) return Results.NotFound(); var professionalId = ClaimGuid(http, "professional_id"); if (professionalId != null && item.ProfessionalId != professionalId) return Results.Forbid(); item.MainComplaint = input.MainComplaint; item.GeneralGoals = input.GeneralGoals; item.SpecificGoals = input.SpecificGoals; item.RecommendedFrequency = input.RecommendedFrequency; item.ReassessmentDate = input.ReassessmentDate; item.Status = input.Status; item.EndDate = input.EndDate; item.ClosingReason = input.ClosingReason; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Professional"));
api.MapGet("/professional/me/settlements", async (ClinicDbContext db, HttpContext http) => { var professionalId = ClaimGuid(http, "professional_id"); if (professionalId is null) return Results.BadRequest(new { message = "Usuário não vinculado a um profissional." }); var professional = await db.Professionals.FindAsync(professionalId); if (professional is null) return Results.NotFound(); var items = await db.Appointments.Include(x => x.Patient).Include(x => x.Service).Where(x => x.ProfessionalId == professionalId && (x.Status == AppointmentStatus.Completed || x.Status == AppointmentStatus.Finalized)).OrderByDescending(x => x.StartsAt).Select(x => new { x.Id, x.StartsAt, patient = x.Patient!.Name, service = x.Service!.Name, gross = x.Amount, percent = professional.DefaultSplitPercent, net = x.Amount * professional.DefaultSplitPercent / 100 }).ToListAsync(); return Results.Ok(new { professional = professional.Name, percent = professional.DefaultSplitPercent, gross = items.Sum(x => x.gross), net = items.Sum(x => x.net), items }); }).RequireAuthorization(p => p.RequireRole("Professional"));
api.MapGet("/reports", async (DateTimeOffset from, DateTimeOffset to, ClinicDbContext db) => { if (to <= from || (to - from).TotalDays > 370) return Results.BadRequest(new { message = "Informe um período válido de até 370 dias." }); var appointments = await db.Appointments.Include(x => x.Professional).Include(x => x.Service).Where(x => x.StartsAt >= from && x.StartsAt < to).ToListAsync(); var receivables = await db.Receivables.Where(x => x.CreatedAt >= from && x.CreatedAt < to).ToListAsync(); var payables = await db.Payables.Where(x => x.CreatedAt >= from && x.CreatedAt < to).ToListAsync(); var completed = appointments.Count(x => x.Status is AppointmentStatus.Completed or AppointmentStatus.Finalized); var cancelled = appointments.Count(x => x.Status is AppointmentStatus.ClinicCancelled or AppointmentStatus.PatientCancelled); var noShows = appointments.Count(x => x.Status == AppointmentStatus.NoShow); return Results.Ok(new { period = new { from, to }, summary = new { appointments = appointments.Count, completed, confirmed = appointments.Count(x => x.Status == AppointmentStatus.Confirmed), cancelled, noShows, occupancyRate = appointments.Count == 0 ? 0 : Math.Round((decimal)completed / appointments.Count * 100, 1), revenue = receivables.Where(x => x.Status == FinancialStatus.Paid).Sum(x => x.PaidAmount), pending = receivables.Where(x => x.Status is FinancialStatus.Pending or FinancialStatus.Overdue).Sum(x => x.Amount - x.PaidAmount), expenses = payables.Where(x => x.Status == FinancialStatus.Paid).Sum(x => x.Amount) }, byProfessional = appointments.GroupBy(x => new { x.ProfessionalId, Name = x.Professional?.Name ?? "Profissional" }).Select(g => new { id = g.Key.ProfessionalId, name = g.Key.Name, appointments = g.Count(), completed = g.Count(x => x.Status is AppointmentStatus.Completed or AppointmentStatus.Finalized), revenue = g.Sum(x => x.Amount) }).OrderByDescending(x => x.appointments), byStatus = appointments.GroupBy(x => x.Status).Select(g => new { status = g.Key.ToString(), count = g.Count() }).OrderByDescending(x => x.count), byService = appointments.GroupBy(x => new { x.ServiceId, Name = x.Service?.Name ?? "Serviço" }).Select(g => new { id = g.Key.ServiceId, name = g.Key.Name, appointments = g.Count(), revenue = g.Sum(x => x.Amount) }).OrderByDescending(x => x.revenue) }); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Finance"));
api.MapGet("/finance", async (ClinicDbContext db) => Results.Ok(new { receivables = await db.Receivables.OrderBy(x => x.DueDate).ToListAsync(), payables = await db.Payables.OrderBy(x => x.DueDate).ToListAsync() })).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Finance", "Reception"));
api.MapPost("/payables", async (Payable input, ClinicDbContext db) => { db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/payables/{input.Id}", input); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Finance"));
api.MapPut("/payables/{id:guid}", async (Guid id, Payable input, ClinicDbContext db) => { var item = await db.Payables.FindAsync(id); if (item is null) return Results.NotFound(); item.Description = input.Description; item.Category = input.Category; item.Amount = input.Amount; item.DueDate = input.DueDate; item.Status = input.Status; await db.SaveChangesAsync(); return Results.Ok(item); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Finance"));
api.MapDelete("/payables/{id:guid}", async (Guid id, ClinicDbContext db) => { var item = await db.Payables.FindAsync(id); if (item is null) return Results.NotFound(); db.Remove(item); await db.SaveChangesAsync(); return Results.NoContent(); }).RequireAuthorization(p => p.RequireRole("ClinicAdmin", "Finance"));

if (!app.Environment.IsEnvironment("Testing")) await InitializeAsync(app, app.Environment.IsDevelopment());
app.Run();

static string NormalizeDatabaseUrl(string value) { if (!value.StartsWith("postgres://") && !value.StartsWith("postgresql://")) return value; var uri = new Uri(value); var credentials = uri.UserInfo.Split(':', 2); return $"Host={uri.Host};Port={uri.Port};Database={uri.AbsolutePath.TrimStart('/')};Username={Uri.UnescapeDataString(credentials[0])};Password={Uri.UnescapeDataString(credentials[1])};SSL Mode=Prefer;Trust Server Certificate=true"; }
static string Slugify(string value) { var normalized = value.Normalize(NormalizationForm.FormD); var chars = normalized.Where(c => CharUnicodeInfo.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark).ToArray(); return Regex.Replace(new string(chars).Normalize(NormalizationForm.FormC).ToLowerInvariant(), "[^a-z0-9]+", "-").Trim('-'); }
static Guid? ClaimGuid(HttpContext http, string name) => Guid.TryParse(http.User.FindFirst(name)?.Value, out var id) ? id : null;
static async Task InitializeAsync(WebApplication app, bool seedDemo) { using var scope = app.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<ClinicDbContext>(); await db.Database.EnsureCreatedAsync(); await db.Database.ExecuteSqlRawAsync("""
ALTER TABLE "Tenants" ADD COLUMN IF NOT EXISTS "PlanCode" text NOT NULL DEFAULT 'trial'; ALTER TABLE "Tenants" ADD COLUMN IF NOT EXISTS "SubscriptionStatus" text NOT NULL DEFAULT 'trialing'; ALTER TABLE "Tenants" ADD COLUMN IF NOT EXISTS "TrialEndsAt" timestamptz NULL;
CREATE TABLE IF NOT EXISTS "AppointmentConfirmations" ("Id" uuid PRIMARY KEY, "TenantId" uuid NOT NULL, "AppointmentId" uuid NOT NULL REFERENCES "Appointments"("Id") ON DELETE CASCADE, "TokenHash" text NOT NULL UNIQUE, "ExpiresAt" timestamptz NOT NULL, "ViewedAt" timestamptz NULL, "RespondedAt" timestamptz NULL, "Response" integer NULL, "RespondentName" text NULL, "Message" text NULL, "IpAddress" text NULL, "UserAgent" text NULL, "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NULL);
CREATE INDEX IF NOT EXISTS "IX_AppointmentConfirmations_TenantId" ON "AppointmentConfirmations" ("TenantId"); CREATE INDEX IF NOT EXISTS "IX_AppointmentConfirmations_TenantId_AppointmentId" ON "AppointmentConfirmations" ("TenantId", "AppointmentId");
CREATE TABLE IF NOT EXISTS "TherapeuticPlans" ("Id" uuid PRIMARY KEY, "TenantId" uuid NOT NULL, "PatientId" uuid NOT NULL REFERENCES "Patients"("Id"), "ProfessionalId" uuid NOT NULL REFERENCES "Professionals"("Id"), "SpecialtyId" uuid NOT NULL REFERENCES "Specialties"("Id"), "StartDate" date NOT NULL, "MainComplaint" text NOT NULL, "GeneralGoals" text NOT NULL, "SpecificGoals" text NOT NULL, "RecommendedFrequency" text NOT NULL, "ReassessmentDate" date NULL, "Status" text NOT NULL, "EndDate" date NULL, "ClosingReason" text NULL, "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NULL);
CREATE INDEX IF NOT EXISTS "IX_TherapeuticPlans_TenantId" ON "TherapeuticPlans" ("TenantId");
"""); if (!seedDemo) return; var tenant = await db.Tenants.IgnoreQueryFilters().SingleOrDefaultAsync(x => x.Slug == "demo"); if (tenant is null) { tenant = new Tenant { Name = "Clínica Ello", Slug = "demo", Email = "contato@elloclinic.com.br" }; db.Tenants.Add(tenant); await db.SaveChangesAsync(); db.Users.Add(new AppUser { TenantId = tenant.Id, Name = "Administrador", Email = "admin@ello.local", PasswordHash = Passwords.Hash("Ello@123"), Role = UserRole.ClinicAdmin }); await db.SaveChangesAsync(); } var professional = await db.Professionals.IgnoreQueryFilters().Where(x => x.TenantId == tenant.Id && x.Email == "mariana@ello.local").OrderBy(x => x.CreatedAt).FirstOrDefaultAsync(); if (professional is not null && !await db.Users.IgnoreQueryFilters().AnyAsync(x => x.TenantId == tenant.Id && x.Email == "mariana@ello.local")) { db.Users.Add(new AppUser { TenantId = tenant.Id, ProfessionalId = professional.Id, Name = professional.Name, Email = "mariana@ello.local", PasswordHash = Passwords.Hash("Mariana@123"), Role = UserRole.Professional }); await db.SaveChangesAsync(); } }
record LoginRequest(string Tenant, string Email, string Password); record TrialRequest(string ClinicName, string Name, string Email, string Phone, string Password, string Plan); record StatusRequest(AppointmentStatus Status); record PublicConfirmationRequest(string Response, string? RespondentName, string? Message); record ProfessionalAccessRequest(string Email, string Password);
public partial class Program { }
