FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist/ello-clinic/browser /usr/share/nginx/html
ENV API_HOST=ello-clinic-api.onrender.com
EXPOSE 80
