server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ { proxy_ssl_server_name on; proxy_set_header Host ${API_HOST}; proxy_pass https://${API_HOST}; }
  location / { try_files $uri $uri/ /index.html; }
}
